# Generated by Django 4.1.3 on 2022-12-20 11:46

from django.db import migrations, models
import pastquestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('courseId', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('courseCode', models.CharField(max_length=6)),
                ('semester', models.CharField(choices=[('Alpha', 'Alpha'), ('Omega', 'Omega')], max_length=5)),
                ('session', models.CharField(max_length=10)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], max_length=3)),
                ('questionFile', models.FileField(upload_to=pastquestion.models.format_filename)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
