# Generated by Django 4.1.3 on 2023-10-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastquestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
